{% set version = "2.0.5" %}
{% set sha256 = "9d9e59498da2871c51d6170a8815da83a72c2c2d29f335e7abf0202e1a8fdb7f" %}

package:
  name: sh
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sh/sh-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8.1
    - pip
    - poetry-core >=1.0.0a5
  run:
    - python >=3.8.1
    - __unix

test:
  imports:
    - sh

about:
  home: https://sh.readthedocs.io/
  doc_url: https://sh.readthedocs.io/
  dev_url: https://github.com/amoffat/sh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python subprocess replacement

extra:
  recipe-maintainers:
    - jakirkham
