{% set version = "2.2.1" %}
{% set sha256 = "287021ae84183dea49787985e33797dda7fe769e4f95f2c94dff8e245ab4cb00" %}

package:
  name: sh
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sh/sh-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8.1
    - pip
    - poetry-core >=1.0.0a5
  run:
    - python >=3.8.1
    - __unix

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - sh

about:
  home: https://sh.readthedocs.io/
  doc_url: https://sh.readthedocs.io/
  dev_url: https://github.com/amoffat/sh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python subprocess replacement

extra:
  recipe-maintainers:
    - jakirkham
