{% set version = "2.4.0" %}
{% set sha256 = "a250aef68509ed93419c9a1d90b0647cd5cbe26107ba94d3717ef5b6d595ffd9" %}

package:
  name: sh
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sh/sh-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0a5
  run:
    - python >={{ python_min }}
    - __unix

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - sh

about:
  home: https://sh.readthedocs.io/
  doc_url: https://sh.readthedocs.io/
  dev_url: https://github.com/amoffat/sh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python subprocess replacement

extra:
  recipe-maintainers:
    - jakirkham
